Kdh step1
KNU-CS09/Baekjoon pull request #17
Opened 2018-06-14 02:21 UTC by dopingcat

my step1 solution review plz

2018-06-14 02:35 UTC, jukqaz requested changes
@dopingcat 
I got it.

2018-06-14 02:39 UTC, dopingcat commented
@jukqaz remove js source complete

2018-06-14 02:39 UTC, jukqaz commented
@dopingcat 
Good 👍 , checked this.

2018-06-14 02:39 UTC, jukqaz approved these changes

2018-06-14 02:40 UTC, cjy9306 approved these changes
congratulations

2018-06-14 02:41 UTC, jukqaz commented on 1/kdh/2_1000.py
> +	parsedInput = line.split()
@dopingcat 
Python is very nice.

2018-06-14 02:42 UTC, dopingcat commented on 1/kdh/2_1000.py
> +	parsedInput = line.split()
Python is simple and good :)

2018-06-15 00:10 UTC, jukqaz commented
@korJiusngPark @AlvinYou 
Review Please.

2018-06-15 01:08 UTC, korJiusngPark approved these changes
👍

2018-06-15 08:16 UTC, AlvinYou approved these changes
👍

2018-06-15 08:21 UTC, merged