step 1 1~8 clear.
KNU-CS09/Baekjoon pull request #7
Opened 2018-06-03 10:37 UTC by AlvinYou

2018-06-04 00:28 UTC, cjy9306 submitted a review, later dismissed
all

2018-06-04 01:08 UTC, korJiusngPark submitted a review, later dismissed
good

2018-06-04 03:01 UTC, kor-haru requested changes
Keep the source code consistent plz. especially semicolon

2018-06-08 11:54 UTC, jukqaz commented on 1/7_11718_yys.js
> +}
Does the code pass without trim in JS?

2018-06-08 11:55 UTC, jukqaz submitted a review, later dismissed

2018-06-08 12:28 UTC, merged

2018-06-08 12:30 UTC, AlvinYou commented
@dopingcat ok. cleared semicolon of all files.